/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Leaderboard: typeof import('./src/components/Leaderboard.vue')['default']
    SeasonPoints: typeof import('./src/components/SeasonPoints.vue')['default']
    TeamBreakdown: typeof import('./src/components/TeamBreakdown.vue')['default']
  }
}
